<<<<<<< HEAD
FrontBundle:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

BookingBundle:
    resource: "@BookingBundle/Resources/config/routing.yml"
=======
AdminBundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
>>>>>>> 8f327dfbd7103562c3058f999483533ca5a9e55a
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
