security:
#    encoders:
#        Tsp\AdminBundle\Entity\UserD:
#            algorithm:        sha1
#            encode_as_base64: false
#            iterations:       1

#        Symfony\Component\Security\Core\User\User: plaintext

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        administrators:
#            entity: { class: AdminBundle:UserD, property: username }
        in_memory:
#            users:
#                user:  { password: user, roles: [ 'ROLE_USER' ] }
#                admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$

        secured_area:
            pattern:    ^/admin
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
            logout:
                path:   /admin/logout
                target: /admin/

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal, roles: ROLE_NO_ACCESS }
