parameters:
#    security.example.class: Tsp\SecurityBundle\Example

services:
#    security.example:
#        class: %security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
