homepage:
    pattern:  /home/
    defaults: { _controller: FrontBundle:Default:index }

register:
    pattern:  /register/
    defaults: { _controller: FrontBundle:Default:register }

customer:
    pattern:  /register_success/
    defaults: { _controller: FrontBundle:Default:customer }

flat_details:
    pattern:  /flat_details/{id}
    defaults: { _controller: FrontBundle:Default:show }